# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: qdb_production
  pool: 5
  min_messages: warning #magic sauce
  username: qdb
  password:
